### PR TITLE
Correcting there unwrapping algorithm

### PR DESCRIPTION
**Pull request by kulkem**
The heuristic unwrapping method leads to unwrapping errors in long NPT trajectories, where atoms traversed multiple periodic boxes. We developed and implemented a new unwrapping algorithm based on the displacement method "https://doi.org/10.48550/arXiv.2111.12052" that corrects this. The current implementation only works for orthorhombic boxes.

### CODE REVIEW

**Comment by jhenin** [comment]
Hi @kulkem , thanks for this PR, somehow I completely missed it until today. I get a lot of notifications from github, so this one must have gotten buried. I will look into this soon.

**Comment by kulkem** [comment]
Thanks Jérôme, let me know if I shall clarify anything in the code.
________________________________

**Comment by jhenin** [comment]
Hi @kulkem , my impression from the paper is that this algorithm is the same as the one currently implemented, just presented differently. Do you have numerical examples showing a difference?

**Comment by kulkem** [comment]
Hi Jérôme,

At small simulation times, the two algorithms do give the same result. But, the heuristic scheme will fail if atoms moved several boxes away from the original simulation cell. To highlight the difference, I made a calc spreadsheet (see attachment) from the example in the publication (page 6166 second paragraph). I also attached two PDB files resembling the same example.

Please let me know if you have any further questions.

Best wishes,
Martin
________________________________

**Comment by jhenin** [comment]
What I meant is, my code does not implement the heuristic method.
Best,
Jérôme

**Comment by kulkem** [comment]
Oh, sorry. I thought that moving back to a previous version meant that you used the heuristic method, but I see now that the code is more similar to the displacement scheme. If I understand it correctly, the difference between your algorithm and the von Bulow algorithm is that you enforce the correct unwrapping of relative distances within a molecule. This will prevent the long/short bonds, we observed using the von Bulow algorithm for Gromacs trajectories.

What your algorithm currently does not consider is that during each MD step in NPT simulations (in most software packages), the coordinates are scaled based on the change in box dimensions. This means that you would need to scale the unwrapped positions of the previous frame in accordance with the change in box size of the current frame, if you would like to absolutely accurately reproduce what the MD software is doing (this is essentially what the additional term in the hybrid method does).

Now, another important aspect is that unwrapping and wrapping should be reversible meaning that if you apply both methods in sequence your final coordinates should not be different from the starting coordinates. In your case, applying a simple floor function for the wrapping (as most wrapping algorithms do) would not fulfill this requirement, but looking at your code, you seem to also wrap coordinates based on displacements.

In the end, the difference between your algorithm and the algorithm we proposed will be the absolute atom positions in space after unwrapping. As long as this does not change the diffusion coefficient, it is more of a philosophical question, which algorithm is more correct.

Best wishes,
Martin
________________________________

**Comment by jhenin** [comment]
If you try this algorithm, you'll see that it is reversible (that is, qunwrap reverses qwrap). I think we're on the same page now. I hope you don't mind if I close this.
Best, Jérôme

**Pull request closed without merging**
